const colors = require('tailwindcss/colors')

/** @type {import('tailwindcss').Config} */
module.exports = {
	darkMode: 'class',
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	theme: {
		colors: {
			transparent: 'transparent',
			current: 'currentColor',
			'background': {
				50: '#f5f6fa',
				100: '#eaebf4',
				200: '#d0d5e7',
				300: '#a7b1d2',
				400: '#7887b8',
				500: '#5768a0',
				600: '#445285',
				700: '#38436c',
				800: '#31395b',
				light: '#171A26',
				lighter: '#252A40',
				DEFAULT: '#0f111a',
			},
			'foreground': {
				50: '#edf5ff',
				100: '#dfebff',
				200: '#c5daff',
				DEFAULT: '#b1cbff',
				400: '#7d9dfc',
				500: '#5e79f6',
				600: '#4153ea',
				700: '#3340cf',
				800: '#2c38a7',
				900: '#2b3684',
			},
			'yellow': '#67EAEA',
			black: colors.black,
			white: colors.white,
			gray: colors.gray,
			emerald: colors.emerald,
			blue: colors.blue,
			indigo: colors.indigo,
			yellow: colors.yellow,
			pink: colors.pink,
			
			
		},
		extend: {
			typography: ({ theme }) => ({
				DEFAULT: {
					// TODO
				  css: {
					'--tw-prose-body': theme('colors.pink[800]'),
					'--tw-prose-headings': theme('colors.pink[900]'),
					'--tw-prose-lead': theme('colors.pink[700]'),
					'--tw-prose-links': theme('colors.pink[900]'),
					'--tw-prose-bold': theme('colors.pink[900]'),
					'--tw-prose-counters': theme('colors.pink[600]'),
					'--tw-prose-bullets': theme('colors.pink[400]'),
					'--tw-prose-hr': theme('colors.pink[300]'),
					'--tw-prose-quotes': theme('colors.pink[900]'),
					'--tw-prose-quote-borders': theme('colors.pink[300]'),
					'--tw-prose-captions': theme('colors.pink[700]'),
					'--tw-prose-code': theme('colors.pink[900]'),
					'--tw-prose-pre-code': theme('colors.pink[100]'),
					'--tw-prose-pre-bg': theme('colors.pink[900]'),
					'--tw-prose-th-borders': theme('colors.pink[300]'),
					'--tw-prose-td-borders': theme('colors.pink[200]'),
					'--tw-prose-invert-body': theme('colors.pink[200]'),
					'--tw-prose-invert-headings': theme('colors.white'),
					'--tw-prose-invert-lead': theme('colors.pink[300]'),
					'--tw-prose-invert-links': theme('colors.white'),
					'--tw-prose-invert-bold': theme('colors.white'),
					'--tw-prose-invert-counters': theme('colors.pink[400]'),
					'--tw-prose-invert-bullets': theme('colors.pink[600]'),
					'--tw-prose-invert-hr': theme('colors.pink[700]'),
					'--tw-prose-invert-quotes': theme('colors.pink[100]'),
					'--tw-prose-invert-quote-borders': theme('colors.pink[700]'),
					'--tw-prose-invert-captions': theme('colors.pink[400]'),
					'--tw-prose-invert-code': theme('colors.white'),
					'--tw-prose-invert-pre-code': theme('colors.pink[300]'),
					'--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
					'--tw-prose-invert-th-borders': theme('colors.pink[600]'),
					'--tw-prose-invert-td-borders': theme('colors.pink[700]'),
				  },
				},
			  }),
		}
	},
	plugins: [require(`@tailwindcss/typography`)],
}
